AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  A Lambda function to run analysis scripts.

Resources:
  AnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/ # Lambdaのソースコードが入っているディレクトリ
      Handler: main.lambda_handler # 実行するハンドラ (ファイル名.関数名)
      Runtime: python3.13.5
      Timeout: 30 # タイムアウトを30秒に設定 (必要に応じて変更)
      MemorySize: 256 # メモリを256MBに設定 (必要に応じて変更)
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: /my-app/*
